version: '3.7'
services:
#|--------------------------------------------------------
#| phpMyAdmin
#|--------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      PMA_HOST: mysql
      UPLOAD_LIMIT: 500M
    volumes:
    - /etc/localtime:/etc/localtime
    depends_on:
    - mysql
    networks:
      zbx_net:
        ipv4_address: 172.18.0.2
    ports:
    - 8080:80
#|--------------------------------------------------------
#| MySQL
#|--------------------------------------------------------
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    restart: unless-stopped
    command:
     - mysqld
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_bin
     - --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
    - /etc/localtime:/etc/localtime
    - /home/administrator/data/mysql:/var/lib/mysql
    networks:
      zbx_net:
        ipv4_address: 172.18.0.3
    ports:
    - 3306:3306
    security_opt:
    - seccomp:unconfined

#|--------------------------------------------------------
#| NETWORKS
#|--------------------------------------------------------
networks:
  zbx_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24